# Generated by Django 5.1.6 on 2025-03-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the task', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the task')),
                ('date_added', models.DateTimeField(auto_now_add=True, help_text='Automatically records creation date/time')),
                ('done', models.BooleanField(default=False, help_text='Checkbox for task completion')),
                ('done_date', models.DateTimeField(blank=True, help_text='Records date/time when task was marked done', null=True)),
                ('canceled', models.BooleanField(default=False, help_text='Marks if task was canceled')),
                ('canceled_date', models.DateTimeField(blank=True, help_text='Records date/time when task was canceled', null=True)),
            ],
        ),
    ]
